--- 
title: "EMM-JRC congress notes"
author: "Corrado Lanera"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
url: https\://corradolanera.github.io/emm/
github-repo: CorradoLanera/emm
link-citations: yes
description: "Notes taken during the Europe Media Monitoring workshop in Gazzada, provided by JRC-Ispra Text mining Team."
---

# Introduction {-}

These notes are about the workshop on the Europe Media Monitoring tool as
presented in Gazzada in occasion of the EMM congress provided by the Text
Mining Team of the JRC (Joint Research Center).

The congress span on three days (29-30 November and 1 December 2017) and it is
divided in two main part:

1. Mornings: conference in which many application and characteristics of EMM
  has been communicated.
2. Afternoons: Workshops, which are three parallel ones on the usability on:
    - overview of the system and the on-line platform,
    - use of the desktop app and relative API,
    - internal procedures used by EMM.

Organization of the notes: one chapter per part of the congress, each one is
subdivided in sub-chapter corresponding to the talks (in the first chapter) or
corresponding to the the topics of the workshop.



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
